# Generated by Django 5.1.4 on 2025-02-09 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_checkout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wallet',
        ),
    ]
