# Generated by Django 5.1.4 on 2025-02-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_checkout_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='job',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
