# Generated by Django 5.1.4 on 2025-02-09 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_checkout_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
