# Generated by Django 5.1.4 on 2025-01-02 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='first_name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='address',
            new_name='letter',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='github_url',
            new_name='website_url',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='phone_number',
        ),
    ]
