# Generated by Django 5.1.4 on 2024-12-29 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_company_joblisting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categories',
            new_name='Categorie',
        ),
    ]
