# Generated by Django 5.1.4 on 2024-12-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_joblisting_employer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='category',
        ),
        migrations.AddField(
            model_name='joblisting',
            name='category',
            field=models.ManyToManyField(to='job.categorie'),
        ),
    ]
