# Generated by Django 5.1.4 on 2024-12-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_alter_categorie_slug_alter_company_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='company/'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='job_type',
            field=models.CharField(blank=True, choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Remote', 'Remote')], null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='vacancy',
            field=models.IntegerField(default=0),
        ),
    ]
