# Generated by Django 5.1.4 on 2025-01-18 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_remove_joblisting_category_appliedjob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='applicants',
        ),
    ]
