# Generated by Django 5.1.4 on 2025-01-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_alter_appliedjob_final_dateline'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjob',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
