# Generated by Django 5.1.4 on 2025-01-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_appliedjob_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjob',
            name='Submit_Job',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appliedjob',
            name='is_jobAssign',
            field=models.BooleanField(default=False),
        ),
    ]
