# Generated by Django 5.1.4 on 2025-01-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_appliedjob_submit_job_appliedjob_is_jobassign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjob',
            name='is_complete',
            field=models.BooleanField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
