# Generated by Django 5.1.4 on 2025-01-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_alter_appliedjob_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjob',
            name='submit_status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
