# Generated by Django 5.1.4 on 2025-01-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_appliedjob_submit_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjob',
            name='is_complete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
