# Generated by Django 5.1.4 on 2025-01-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0019_alter_appliedjob_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjob',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
