# Generated by Django 5.1.4 on 2025-02-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0020_alter_appliedjob_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjob',
            name='applied_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
