# Generated by Django 5.1.4 on 2025-02-16 09:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0022_remove_appliedjob_applied_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
