# Generated by Django 5.1.4 on 2025-03-05 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0023_alter_company_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joblisting',
            old_name='loaction',
            new_name='location',
        ),
    ]
