# Generated by Django 5.1.4 on 2025-03-05 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0025_delete_appliedjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('applicant_name', models.CharField(max_length=100)),
                ('task', models.TextField(blank=True, null=True)),
                ('final_dateline', models.DateField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('submit_status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('is_jobAssign', models.BooleanField(default=False)),
                ('Submit_Job', models.TextField(blank=True, null=True)),
                ('candidate', models.ForeignKey(limit_choices_to={'profile__role': 'Job Seeker'}, on_delete=django.db.models.deletion.CASCADE, related_name='applied_jobs_as_candidate', to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(limit_choices_to={'profile__role': 'Employer'}, on_delete=django.db.models.deletion.CASCADE, related_name='applied_jobs_as_employer', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.joblisting')),
            ],
        ),
    ]
